/**
 * Mock Backend Server for Saarthi.AI
 * Simulates AWS Lambda + API Gateway responses for local testing
 */

const express = require('express');
const cors = require('cors');
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage() });

const app = express();
app.use(cors());
app.use(express.json({ limit: '50mb' }));

const PORT = 3001;

console.log('🚀 Starting Mock Backend Server...\n');

// Health check
app.get('/health', (req, res) => {
  res.json({ success: true, data: { status: 'ok' } });
});

// RAG Query endpoint
app.post('/query', (req, res) => {
  const { query, language } = req.body;
  console.log(`📝 Query: "${query}" (${language})`);
  
  setTimeout(() => {
    res.json({
      success: true,
      data: {
        answer: `Mock answer for: "${query}" in ${language}. This is a simulated response for testing purposes. The actual response would come from Claude 3 Sonnet via Bedrock.`,
        sources: [
          { title: 'Mock Government Scheme Document', url: 'https://example.com/scheme1' },
          { title: 'Mock Policy PDF', url: 'https://example.com/policy1' }
        ],
        confidence: 0.85
      }
    });
  }, 1000);
});

// PDF Processing endpoint
app.post('/pdf', (req, res) => {
  const { file, filename } = req.body;
  console.log(`📄 PDF Upload: ${filename || 'unknown'}`);
  
  setTimeout(() => {
    res.json({
      success: true,
      data: {
        extracted_text: 'Mock extracted text from PDF. This is a simulated response. The actual text would be extracted using Amazon Textract.',
        summary: 'This is a mock summary of the PDF content. It contains key information extracted from the document. The actual summary would be generated by Claude 3 Sonnet.',
        key_points: [
          'Mock key point 1: Important information about the document',
          'Mock key point 2: Key details and requirements',
          'Mock key point 3: Summary of main points',
          'Mock key point 4: Additional relevant information',
          'Mock key point 5: Conclusion and next steps'
        ]
      }
    });
  }, 2000);
});

// Scheme Recommendation endpoint
app.post('/recommend', (req, res) => {
  const { age, state, income, occupation } = req.body;
  console.log(`💡 Recommendation: Age=${age}, State=${state}, Income=${income}, Occupation=${occupation}`);
  
  setTimeout(() => {
    res.json({
      success: true,
      data: {
        schemes: [
          {
            name: 'Mock Scheme 1 - Housing Assistance',
            description: 'A mock government housing scheme for testing purposes. Provides financial assistance for home construction.',
            eligibility: `Age: 18+, Income: < 5L, State: ${state || 'All'}`,
            apply_steps: [
              'Step 1: Visit official website and register',
              'Step 2: Fill out the application form with required details',
              'Step 3: Upload necessary documents (Aadhaar, income certificate)',
              'Step 4: Submit application and wait for approval'
            ],
            link: 'https://example.com/scheme1'
          },
          {
            name: 'Mock Scheme 2 - Education Support',
            description: 'Another mock scheme providing educational support and scholarships.',
            eligibility: `Age: 25+, Income: < 10L, Occupation: ${occupation || 'Any'}`,
            apply_steps: [
              'Step 1: Register online with student details',
              'Step 2: Upload academic documents',
              'Step 3: Submit income certificate',
              'Step 4: Wait for scholarship approval'
            ],
            link: 'https://example.com/scheme2'
          },
          {
            name: 'Mock Scheme 3 - Healthcare Benefits',
            description: 'Mock healthcare scheme providing medical insurance coverage.',
            eligibility: `Age: ${age || '18'}+, Income: < 3L`,
            apply_steps: [
              'Step 1: Download application form',
              'Step 2: Fill personal and family details',
              'Step 3: Attach medical records if applicable',
              'Step 4: Submit to nearest government office'
            ],
            link: 'https://example.com/scheme3'
          }
        ]
      }
    });
  }, 1500);
});

// Grievance Generator endpoint
app.post('/grievance', (req, res) => {
  const { issue_type, description, location } = req.body;
  console.log(`📋 Grievance: ${issue_type} at ${location}`);
  
  const currentDate = new Date().toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  setTimeout(() => {
    res.json({
      success: true,
      data: {
        complaint_letter: `COMPLAINT LETTER

To,
The Concerned Authority,
${location || 'Your City'}

Subject: Complaint regarding ${issue_type || 'Public Issue'}

Respected Sir/Madam,

I am writing to bring to your kind attention a serious issue that requires immediate action.

Issue Type: ${issue_type || 'General Complaint'}
Description: ${description || 'Please provide description of the issue'}
Location: ${location || 'Please provide location'}

This issue has been causing significant inconvenience to the residents of the area. We request your immediate attention and action to resolve this matter at the earliest.

We hope that appropriate measures will be taken to address this concern promptly.

Thanking you,

Yours faithfully,
[Your Name]
[Your Contact Number]
[Your Address]

Date: ${currentDate}

---
Note: This is a mock complaint letter generated for testing purposes. The actual letter would be generated by Claude 3 Sonnet.`
      }
    });
  }, 1000);
});

// Voice STT endpoint
app.post('/voice/stt', upload.single('audio'), (req, res) => {
  console.log(`🎤 STT Request: ${req.file?.originalname || 'audio file'}`);
  
  setTimeout(() => {
    res.json({
      success: true,
      data: {
        text: 'This is a mock transcription of the audio file. The actual speech-to-text conversion would happen using Amazon Transcribe.'
      }
    });
  }, 2000);
});

// Voice TTS endpoint
app.post('/voice/tts', (req, res) => {
  const { text, language } = req.body;
  console.log(`🔊 TTS Request: "${text.substring(0, 50)}..." (${language})`);
  
  setTimeout(() => {
    // Return mock base64 audio (silent audio WAV file)
    const mockAudioBase64 = 'UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=';
    res.json({
      success: true,
      data: {
        audio: mockAudioBase64
      }
    });
  }, 1500);
});

app.listen(PORT, () => {
  console.log(`✅ Mock backend server running on http://localhost:${PORT}\n`);
  console.log('📝 Available endpoints:');
  console.log(`   GET  /health`);
  console.log(`   POST /query`);
  console.log(`   POST /pdf`);
  console.log(`   POST /recommend`);
  console.log(`   POST /grievance`);
  console.log(`   POST /voice/stt`);
  console.log(`   POST /voice/tts\n`);
  console.log('💡 Set NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:3001 in frontend/.env.local');
});
